image: node:latest

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm ci
    - npm run build
    - firebase deploy
  variables:
    CI: "false"
