image: node:latest

cache:
  paths:
    - node_modules/

deploy_production:
  stage: deploy
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm ci
    - npm run build
    - firebase deploy --token "$FIREBASE_TOKEN" --project "$FIREBASE_PROJECT"
  variables:
    CI: "false" # Tell react-scripts build to not treat warnings as errors
