export const ADD_PAGE = "ADD_PAGE";
export const ADD_PAGES = "ADD_PAGES";
export const CLEAR_PAGES = "CLEAR_PAGES";
export const SET_PAGE = "SET_PAGE";
export const MOVE_PAGE_UP = "MOVE_PAGE_UP";
export const MOVE_PAGE_DOWN = "MOVE_PAGE_DOWN";
export const REMOVE_PAGE = "REMOVE_PAGE";

export const START_DRAWING = "START_DRAWING";
export const STOP_DRAWING = "STOP_DRAWING";
export const SET_SHOW_SAVE_CONFIRMATION = "SET_SHOW_SAVE_CONFIRMATION";
export const SAVE_DRAW_RECT = "SAVE_DRAW_RECT";
export const SAVE_CANVAS_MOUSEUP_POSITION = "SAVE_CANVAS_MOUSEUP_POSITION";

export const SET_FILL_COLOUR = "SET_FILL_COLOUR";
